# -*- coding: utf-8 -*-
"""Basic Python Language For Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gRS2bKu2hsjZF8Rm-KkC-V7K06hod8i
"""

from google.colab import drive
drive.mount('/content/drive')

"""Tipe Data Python"""

x = 1
type(x)

y = 0.0
type(y)

z = 3+4j
type(z)

#String adalah tipe data yang berisi teks
a = "Rinaldi"
type(a)

# Boolean adalah tipe data yang digunakan untuk menyimpan nilai kebenaran, yaitu hanya dua kemungkinan:
# True (benar)
# False (salah)
x = True
type(x)

y= False
type(y)

# None adalah tipe data khusus yang digunakan untuk menyatakan bahwa tidak ada nilai, kosong, atau nilai belum ditentukan.
e = None
type(e)

#addition/operasi penjumlahan
2+2

a = 5
b = 3
c = a + b
print(c)

[1, 2] + [3, 4]

#subtraction/operasi pengurangan
a = 10
b = 5
c = a-b
print(c)

#multiplication/operasi perkalian
a = 5
b = 2
c = a*b
print(c)

#division/operasi pembagian
a = 10
b = 5
c = a/b
print(c)

#expontiation/operasi perpangkatan
a = 2
b = 3
c = a**b
print(c)

5 ** 2

10 ** 0

9 ** 0.5 # (akar kuadrat)

#floor division --return the result in whole number
#Floor division adalah operasi pembagian yang menghasilkan angka bulat (whole number)
#dengan cara pembulatan ke bawah (floor), tidak peduli hasilnya positif atau negatif.
7//2

7.0//2

-10 // 3

#modulus -- the output is remainder
#Modulus adalah operasi untuk menghasilkan sisa pembagian antara dua angka.
5%2

20 % 5

-10 % 3

#single quotes string
#Single quotes string adalah string yang ditulis menggunakan tanda kutip satu (' ').
sub = 'Machine learning'
type(sub)

#double quotes string
#Double quotes string adalah string yang ditulis menggunakan tanda kutip dua (" ").
my_college = "Universitas Teknologi Yogyakarta"
type(my_college)

#triple quotes string
#Triple quotes string adalah string yang ditulis menggunakan tiga tanda kutip berurutan, bisa:
#'''...''' (triple single quotes), atau
#"""...""" (triple double quotes)
#Kegunaannya:
# Untuk membuat multi-line string (teks beberapa baris).
# Untuk menulis teks panjang tanpa perlu \n.
# Sering dipakai untuk docstring pada fungsi Python.
my_sentence = '''This sentence is multipline line,
this is also known as string'''
type(my_sentence)

#find the length of string
#Untuk mencari panjang sebuah string di Python, gunakan fungsi len().
my_sub = "Machine learning"
len(my_sub)

my_sub[0]

my_sub[1]

my_sub[15]

my_sub = "Machine learning"
my_sub[-1]

my_sub[-9]

#my_sub[0:7:1] berarti mengambil karakter dari indeks 0 sampai 6 dengan langkah 1.
#[start : stop : step]
my_sub[0:7:1]

my_sub[0:7]#bydefault stepsize is 1/jika step tidak ditulis, maka default-nya adalah 1.

#lower()--this method used to convert string into lower case
#Metode .lower() digunakan untuk mengubah semua huruf dalam string menjadi huruf kecil (lowercase).
my_sub = "PYTHON"
my_sub.lower()

#upper()--this method used to convert string into uppercase
#Metode .upper() digunakan untuk mengubah semua huruf dalam string menjadi huruf besar (uppercase).
my_sub = "python"
my_sub.upper()

#count()--this method count particular character in string
#Metode .count() digunakan untuk menghitung berapa kali karakter
#atau substring tertentu muncul dalam sebuah string.
my_string = "Machine learning"
my_string.count('a')

#list
my_list = [78, 89, 23, 45, 56]
type(my_list)

mixed_list = [23, 3.14, "apple", True, None]
type(mixed_list)

print(my_list)
print(mixed_list)

#find the length of the list
#Untuk mengetahui berapa banyak elemen dalam sebuah list, gunakan fungsi len(), sama seperti pada string.
len(my_list)
len(mixed_list)

#positive indexing
#Positive indexing digunakan untuk mengakses elemen dalam list
#(atau string/tuple) mulai dari awal, dengan indeks dimulai dari 0.
my_list = [78,89,23,34,10]
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])
print(my_list[4])

#negative indexing — accessing elements from the end
#Negative indexing digunakan untuk mengakses elemen dalam list
#(atau string/tuple) mulai dari akhir, dengan indeks dimulai dari -1.
my_list = [78,89,23,34,10]
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-4])
print(my_list[-5])

my_list = [2, 3, 7, 1, 4, 5]
my_list[0:5:1]

#bydefault stepsize is one
#Dalam slicing (pada string, list, tuple), jika step tidak disebutkan,
#Python akan menggunakan step = 1 secara default.
my_list[0:5]

my_list[0:]

my_list[:5]

my_list[: : -1]

#function in list
#min()--return the minimum number of the list
#Metode min() digunakan untuk mengembalikan nilai minimum dari sebuah list (atau iterable lainnya).
my_list =[98, 34, 56, 45, 12]
min(my_list)

#max()--return maximum number of the list
#Metode max() digunakan untuk mengembalikan nilai maksimum dari sebuah list (atau iterable lainnya).
max(my_list)

my_list

#sum()--return addition of the all item of the list
#Fungsi sum() digunakan untuk menjumlahkan semua elemen dalam list (atau iterable).
sum(my_list)

#sorted()--this function arrange list increasing or decreasing order
#Fungsi sorted() digunakan untuk mengurutkan elemen list (atau iterable) tanpa mengubah list asli.
list1 = [9, 7, 12, 4, 8, 3]
sorted(list1, reverse = True)

list1

#append()--this method add item end of the list and take item as argument
#Metode .append() digunakan untuk menambahkan satu elemen baru di akhir list.
#Elemen yang ditambahkan diberikan sebagai argumen.
my_list = [90, 87, 65, 34]
print(my_list)
my_list.append(100)
print(my_list)

my_list

my_list[2] = 200
print(my_list)

fruits = ["apple", "banana", "cherry"]
fruits.append("date")
print(fruits)

#extend()--this method merge a list into another list
#Metode .extend() digunakan untuk menambahkan semua elemen dari satu list ke list lain.
#Berbeda dengan .append(), .extend() menambahkan elemen satu per satu, bukan sebagai satu item tunggal.
list1 = [90, 78, 65]
list2 = [56, 89, 45]
list1.extend(list2)
print(list1)

#pop()--this method remove item from the list, take index as argument
#Metode .pop() digunakan untuk menghapus elemen dari list berdasarkan
#indeks dan mengembalikan elemen yang dihapus.
my_list  = [78, 56, 34, 12]
my_list.pop()

fruits = ["apple", "banana", "cherry", "date"]
removed_item = fruits.pop(1)
print(removed_item)
print(fruits)

#remove()--this method remove item of the list, take item as a argument
#Metode .remove() digunakan untuk menghapus elemen tertentu dari list berdasarkan nilainya, bukan indeks.
list1 = [90, 87, 65, 23]
list1.remove(87)
list1

fruits = ["apple", "banana", "cherry", "date"]
fruits.remove("banana")
print(fruits)

#reverse()-- this method reverse the list
#Metode .reverse() digunakan untuk membalik urutan elemen dalam list secara langsung (in-place).
my_list = [90, 87, 56, 23]
my_list.reverse()
print(my_list)

#dictionary
#Dictionary adalah tipe data di Python yang digunakan untuk menyimpan data dalam bentuk pasangan key: value.
my_dict = {"Name":"Rinaldi", "College":"Universitas Teknologi Yogyakarta", "Major":"Informatika"}
type(my_dict)

print(my_dict)

print(my_dict["Name"])
print(my_dict["College"])
print(my_dict["Major"])

#method in dictionary
#keys()--this method find the keys of dictionary
#Metode .keys() digunakan untuk mengambil semua key dari dictionary sebagai view object.
list(my_dict.keys())

#values()--this method find value of the dictionary
#Metode .values() digunakan untuk mengambil semua value dari dictionary sebagai view object
list(my_dict.values())

#items()--this method find items of the dictionary
#Metode .items() digunakan untuk mengambil semua pasangan key: value dari dictionary sebagai view object.
list(my_dict.items())

#get()--this method find value in the dictionary and key take as argument
#Metode .get() digunakan untuk mengambil nilai dari dictionary berdasarkan key.
#Jika key tidak ada, tidak menimbulkan error, melainkan mengembalikan None (atau nilai default jika diberikan).
my_dict.get("Major")

print(my_dict.get("Age", "Age is not present"))

#update()--this method update the dictionary and take dictionary as argument
#Metode .update() digunakan untuk menambahkan atau memperbarui key-value dari dictionary
#menggunakan dictionary lain sebagai argumen.
my_dict.update({"Age":20})
print(my_dict)

my_dict.update({"Name":"Joko"})
print(my_dict)

"""Conditional"""

#conditional statement — making decisions in Python
#Conditional statements digunakan untuk menjalankan kode tertentu hanya jika kondisi tertentu terpenuhi
#if condition:
    # kode dijalankan jika condition True
#elif another_condition:
    # kode dijalankan jika another_condition True
#else:
    # kode dijalankan jika semua kondisi False
age = int(input("Enter your age:"))
if age>60:
  print("You are too old for marry")
elif age<18:
  print("You are too young for marry")
else:
  print("we will find perfact match for you")

"""Catatan:

if → memeriksa kondisi pertama

elif → memeriksa kondisi tambahan (optional)

else → menangani semua kondisi lain (optional)
"""

score = 85

if score >= 90:
    print("Grade A")
elif score >= 75:
    print("Grade B")
else:
    print("Grade C")

my_sub = "Python"
print(my_sub[0])
print(my_sub[1])
print(my_sub[2])
print(my_sub[3])
print(my_sub[4])
print(my_sub[5])

"""Catatan:

Indeks mulai dari 0.

Bisa juga menggunakan loop untuk mencetak semua karakter:
"""

my_sub = "python"
for i in my_sub:
    print(i)

#range() — generate a sequence of numbers
#Fungsi range() digunakan di Python untuk membuat urutan angka yang sering dipakai di for loop.
#penggunaan for loop dengan range() di Python
for i in range(0, 6, 1):
  print(i)

#Penjelasan range(0, 6):
#0 → start (awal)
#6 → stop (akhir, tidak termasuk)
#Step default = 1, jadi tidak perlu ditulis
for i in range(0, 6):
  print(i)

for i in range(6):
  print(i)

#mengakses karakter string beserta indeksnya menggunakan for loop dan range() di Python
#Penjelasan:
#len(my_sub) → panjang string "python" = 6
#range(len(my_sub)) → menghasilkan angka dari 0 sampai 5
#my_sub[i] → mengakses karakter pada indeks i
my_sub = "python"
for i in range(len(my_sub)):
  print(my_sub[i], "->", i)

#enumerate()— get index and value while looping
#Fungsi enumerate() digunakan untuk mengakses elemen beserta indeksnya saat melakukan looping di Python.
#Ini membuat kode lebih pythonic dibanding menggunakan range(len(...)).
my_sub = "python"
for i, char in enumerate(my_sub):
    print(char, "->", i)

fruits = ["apple", "banana", "cherry"]
for i, fruit in enumerate(fruits):
    print(i, ":", fruit)

"""While Loop"""

#while loop— repeating code while a condition is True
#while loop digunakan untuk menjalankan kode berulang kali selama kondisi bernilai True.
i = 0 #inilization
while i<5: #condition
  print(i)
  i+=1 #increment

"""Penjelasan:

Initialization: i = 0 → memulai variabel counter

Condition: i < 5 → loop berjalan selama True

Body: print(i) → perintah yang dijalankan setiap iterasi

Increment: i += 1 → agar kondisi akhirnya menjadi False dan loop berhenti
"""

#loops and control statement
#break -- this statement break the loop
#break digunakan untuk menghentikan loop secara langsung, walaupun kondisi loop masih True.
i = 0
while i<5:
  i+=1 #increment
  if i==3:
    break
  else:
    print(i)

"""Penjelasan:

i = 0 → mulai

Loop while i < 5 berjalan

i += 1 → menambah i setiap iterasi

if i == 3: → saat i = 3, break menghentikan loop

else: print(i) → hanya mencetak i sebelum i = 3
"""

#continue statement-- this statement skip the current iteration
#continue digunakan untuk melewatkan sisa kode di dalam loop saat ini dan melanjutkan ke iterasi berikutnya.
i = 0
while i<5:
  i+=1
  if i==3:
    continue
    print(i)
  else:
    print(i)

"""Penjelasan:

i = 0 → mulai

Loop while i < 5 berjalan

i += 1 → menambah i setiap iterasi

if i == 3: → saat i = 3, continue dilewati, sehingga print(i) di bawah continue tidak dijalankan

Loop melanjutkan ke iterasi berikutnya
"""

#pass statement -- this statement pass the code/this statement does nothing
#pass digunakan sebagai placeholder di Python. Artinya, Python tidak melakukan apa-apa saat mencapai pass.
#Biasanya dipakai untuk struktur kode yang belum diisi agar tidak menimbulkan error.
i = 0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

"""Penjelasan:

pass tidak mengubah alur program.

Dalam contoh di atas, loop tetap berjalan normal.

Berguna untuk:

Menulis skeleton kode sementara

Membuat blok if, loop, function tanpa isi untuk sementara

Funtion/Fungsi
"""

#user defined function without argument
#Fungsi user-defined adalah fungsi yang dibuat sendiri oleh programmer.
#Fungsi tanpa argument berarti tidak menerima nilai dari luar, tapi bisa melakukan operasi di dalam fungsi.
def add(): #fungsi
  a = int(input("Enter the first number: "))
  b = int(input("Enter the second number: "))
  return a+b #operasi penambahan

add()

def add(): #fungsi
    a = int(input("Enter the first number: "))
    b = int(input("Enter the second number: "))
    return a - b #operasi pengurangan

add()

#positional argument-passing values based on position
#Positional arguments adalah nilai yang dikirim ke fungsi berdasarkan urutan parameternya.
def calculation(a, b):
  print("addition", a+b)
  print("subtraction", a-b)
  print("multiplication", a*b)
  print("Division", a/b)
  return "Calculation is complete"

print(calculation(17, 5))

#default argument— parameters with default values
#Default arguments adalah parameter fungsi yang memiliki nilai bawaan,
#sehingga tidak wajib diberikan saat memanggil fungsi.
def area_perimeter(panjang=4, lebar=8):
  luas = panjang*lebar
  perimeter = 2*(panjang + lebar)
  return "Area is", luas, "and perimeter is", perimeter

print(area_perimeter())

print(area_perimeter(10, 20))

print(area_perimeter(10,10))

#keyword argument—passing values using parameter names
#Keyword arguments adalah cara memanggil fungsi dengan menyebutkan nama parameternya,
#sehingga urutan tidak lagi penting.
def interest(p, r, t):
  i = (p*r*t)/100
  return i
print(interest(r = 10, t = 2, p = 1000))

#mixed argument (campuran positional + keyword)
#positional argument follows keyword argument adalah error yang muncul ketika kamu menulis argumen posisi setelah argumen keyword, yang tidak diperbolehkan.
print(interest(1000, t = 2, r = 10))

print(interest(r = 10,p=1000,  2))

def calculation(a, b):
    print("Addition:", a + b)
    print("Subtraction:", a - b)
    print("Multiplication:", a * b)
    print("Division:", a / b)
calculation(a=10, b=5)

#variable length argument-argumen yang jumlahnya tidak tetap.
#non keyword positional variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(2,3, 4, 8, 9, 7)

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

sum_number(3, 5, 6, 7, 8, 9)

#keyword variable length argument(kwargs)
#**kwargs memungkinkan kita menerima argumen dengan keyword dalam jumlah tidak terbatas.
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

test(a = 10, b = 20, c = 30)

def pass_students(**kwargs):
  pass_student_list = []
  for name, marks in kwargs.items():
    if marks>35:
      pass_student_list.append(name)
  return pass_student_list

pass_students(A = 30, B = 40, C = 50, D= 80, E = 20)

"""NumPy = Numerical Python
import numpy as np adalah statement untuk mengimpor library NumPy dan memberi alias np.

NumPy = Numerical Python, digunakan untuk:

1.operasi matematika cepat

2.array/matrix multidimensi

3.operasi linear algebra

4.statistik

5.manipulasi dataset numerik
"""

import numpy as np

#one dimensional array (Array 1 Dimensi)
#Array 1 dimensi adalah array dengan satu baris data, mirip list,
#tetapi memiliki kemampuan matematika yang jauh lebih cepat.
one_array = np.array([1, 2,3, 4])
print(one_array)

#two dimensional array (array 2 dimensi)
#Array 2 dimensi adalah array yang memiliki baris dan kolom, mirip seperti tabel atau matriks.
twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

#row vector (Vektor Baris)
#Row vector adalah array 2 dimensi dengan 1 baris dan beberapa kolom.
row_vector = np.array([[1, 2, 3]])
print(row_vector)

column_vector = np.array([[1], [2], [3]])
print(column_vector)

#Transpose adalah operasi untuk menukar baris menjadi kolom dan kolom menjadi baris.
#Dalam matematika biasa disebut matriks A-tranpose.
column_vector = row_vector.transpose()
print(column_vector)

#ndim -- find the dimension of vector
#ndim — Mengetahui Jumlah Dimensi dari Array / Vector
column_vector.ndim

#size--find the number of item
#size — Mengetahui Jumlah Total Elemen pada Array
column_vector.size

print(column_vector)

#shape
#shape — Mengetahui Bentuk (Baris, Kolom, Dimensi) dari Array
column_vector.shape

print(row_vector)

row_vector.shape

twod_array = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_array)

print(twod_array[0][1])

print(twod_array[1][2])

print(twod_array[0,1])

print(twod_array[0:2,0:2])

#numpy.random.randint() — Membuat Angka Acak (Integer)
#Fungsi randint() digunakan untuk menghasilkan bilangan bulat acak (integer random).
threed_array = np.random.randint(1, 10, (3, 3))
print(threed_array)

print(threed_array[0:2, 0:2 ])

import numpy as np
mat1 = np.matrix("1, 2, 3; 4, 5, 6; 7, 8, 9")
print(mat1)

mat2 = np.matrix([[1, 2, 3],[4, 5, 6]])
print(mat2)

mat3 = np.random.random((3, 3))
print(mat3)

mat4 = np.random.randint(1, 20, (3, 3))
print(mat4)

#np.zeros adalah fungsi di NumPy untuk membuat array yang semua elemennya bernilai 0.
zeros_array = np.zeros((3, 3), dtype = int)
print(zeros_array)

ones_array = np.ones(( 3, 3), dtype = int)
print(ones_array)

print(ones_array*100)

#np.full digunakan untuk membuat array NumPy yang semua elemennya bernilai sama,
#sesuai nilai yang kamu tentukan.
my_array = np.full((3, 3), 10)
print(my_array)

my_array = np.array([1, 2,3, 4])
print(my_array)

power_array = np.power(my_array, 2)
print(power_array)

print(my_array)

exp_array = np.exp(my_array)
print(exp_array)

log_array = np.log(my_array)
print(log_array)

log2_array = np.log2(my_array)
print(log2_array)

log10_array = np.log10(my_array)
print(log10_array)

a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (3,2))
print(a)
print(b)

print(np.dot(a, b))

"""import matplotlib.pyplot as plt
Digunakan untuk mengimpor modul pyplot dari library Matplotlib, yang berfungsi untuk membuat berbagai macam grafik.
"""

import matplotlib.pyplot as plt
import numpy as np

xpoint = np.array([1,3])
ypoint = np.array([2, 4])
plt.plot(xpoint,ypoint)
plt.show()

cgpa = np.array([6,6.5,7,7.8, 8, 8.4, 9, 9.7, 10])
package = np.array([5, 5.4, 6, 6.2, 6.8, 7, 7.5, 8, 8.8])
plt.plot(cgpa,package,"*:g", ms = 15,mec="orange",linewidth =5)
font1 ={"family":"serif", "color":"blue", "size":15}
font2 ={"family":"serif", "color":"Red", "size":20}
plt.title("Universitas Teknologi Yogyakarta data", fontdict = font2)
plt.xlabel("CGPA",fontdict = font1)
plt.ylabel("PACKAGE",fontdict = font1)
#plt.title("Shoolini university students data")
plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 80, 50])
color = np.array(["red", "yellow", "orange", "green"])
plt.bar(fruit, quantity, color = color)
plt.xlabel("Fruit")
plt.ylabel("Quantity")
plt.title("Fruit Quantity")
plt.show()

fruit = np.array(["Apple", "Banana", "Orange", "Watermelon"])
quantity = np.array([100, 120, 80, 50])
color = np.array(["red", "yellow", "orange", "green"])
plt.barh(fruit, quantity, color = color)
plt.xlabel("Quantity")
plt.ylabel("Fruit")
plt.title("Fruit Quantity")
plt.show()

#pie plot
quantity = np.array([20, 35, 15, 30])
fruit = np.array(["Apple", "Banana", "Orange", "Mango"])
myexplode = [0.2, 0, 0, 0]
plt.pie(quantity, labels = fruit, explode = myexplode)
plt.legend(title = "Fruit",loc = "best")
plt.show()

#scatter plot
age_of_car = np.array([4, 6, 8, 10, 12, 14, 16, 18])
speed_of_car = np.array([150, 130, 120, 110, 100, 90, 80, 70])
plt.scatter(age_of_car, speed_of_car)
plt.xlabel("Age of car")
plt.ylabel("Speed of car")
plt.title("Age and speed of car")
plt.show()

#histogram-- it shows frequency distribution
import numpy as np
x = np.random.randint(40, 100, (1, 200))
print(x)
x = x.flatten()
print(x)

plt.hist(x, bins=10, color="skyblue", edgecolor="black")
plt.title("Histogram Nilai")
plt.xlabel("Nilai")
plt.ylabel("Frekuensi")
plt.show()

"""import pandas as pd digunakan untuk mengimpor library Pandas dan memberi alias pd.

Pandas adalah library Python yang sangat populer untuk manipulasi dan analisis data, khususnya data berbentuk tabel (mirip spreadsheet atau SQL).
"""

import pandas as pd

#Series--one dimensional data structure of pandas
my_series = pd.Series(["Appple", "Banana", "Mango", "Orange"], name= "Fruit" )
my_series

#DataFrame--two dimensional data structure of pandas
list_into_list = [["Amar",15],["Akbar",14], ["Anthony",13]]
df = pd.DataFrame(list_into_list, columns = ["Name", "Age"])
df

#how to read csv file
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/Semester7 2026/Data Science/pizza_sales.xlsx")
df

#head()--bring rows(data point) from top of the dataframe
df.head(100)

#tail()--bring the rows(data point) from bottom of the data frame
df.tail(10)

#find the number of rows and column in the data frame
df.shape

#find the name of the all columns
df.columns

#bring the rows(data point) randomly from the data
df.sample(5)

#find the information of the data
df.info()

#how does the data looklike mathematically
df.describe()

#find the duplicate value
print(df.duplicated().sum())

#find the null value
df.isnull().sum()

df.columns

#multiple column with all rows
df[["pizza_sales"]]

#slicing with help of rows
df[0:4]

#find the some number of rows and columns
df.iloc[0:4, 0:3]

df.loc[0:4, ["pizza_sales"]]

#find the unique value in particular column
df["pizza_sales"].unique()

#how to write file in csv format
pizza_sales.to_csv("pizza_salese.csv")